### ISSUE TITLE
Suggestion: `#pragma once > #ifndef CLI_H__`

### ISSUE THREAD

**Issue by chaseblock** [lhr-solar/BPS#116]
This is a style suggestion.

Right now, there is inconsistency with our header file guards. Consider the three examples below:

```c
#ifndef CLI_H__
#define CLI_H__
// stuff
#endif
```

```c
#ifndef __COMMON_H
#define __COMMON_H
// stuff
#endif
```

```c
#ifndef SOC_H
#define SOC_H
// stuff
#endif
```

These are excerpts from the code in this repository. It's hard to keep a consistent style with guards like this. It's also hard to remember that we are supposed to have guards sometimes (see Images.h, which lacks a header guard; this is also an issue).

A solution that I'm fond of is the use of `#pragma once` at the beginning of every header file. This serves the same purpose as the header guards (prevents the file from being read twice when compiling a single object). There is also only one way to write it, and it is an easy thing to check at the beginning of each file, since there's no footer that needs to be checked along with it.

**Comment by ClarkPoon** [comment]
Personally, I am fine with just using `#ifdef` guards. @manthanand also standardized all of the `#define` guards in #311
