### ISSUE TITLE
Current library to Amperes library?

### ISSUE THREAD

**Issue by SijWoo** [lhr-solar/BPS#128]
Even though this has been what we've been using for the past couple years, every time I say current board/library with other members I feel compelled to specify Current means amperes and not time. Current members know current means amps and not time in the context of the BPS but for future members, it may be good to change the library name to prevent any confusion.

**Proposal:** Change Current library and Current board names to Amperes library and Amperes board

**Comment by SijWoo** [comment]
Any thoughts are welcome :)
@ClarkPoon @chaseblock @sugamarora99 @manthanand @alekxoo @AleNeff @etblum12

**Comment by ClarkPoon** [comment]
I think this is a good idea

**Comment by chaseblock** [comment]
I'm not too much of a fan of this move, but I understand the difficulty with the current "current" term, and as long as this improves clarity, I don't mind.
