### ISSUE TITLE
Document fan software

### ISSUE THREAD

**Issue by ClarkPoon** [lhr-solar/BPS#164]

**Comment by shannonxtreme** [comment]
Hi! Is there any way I can help with the documentation?

**Comment by ClarkPoon** [comment]
Hi @shannonxtreme we are a part of the solar vehicle team for the University of Texas at Austin and any help with our documentation would be appreciated. Right now, our documentation is on google docs, and if you email me at clarkpoon@utexas.edu, I can share the document with you. Please let me know if you have any questions.
