### ISSUE TITLE
[RTOS] Add SPI Mutex to prevent any tasks from accessing the periperal at the same time

### ISSUE THREAD

**Issue by SijWoo** [lhr-solar/BPS#188]
Please go to google drive in BPS>Documentation/Reports>BPS RTOS for more information and pseudo code.

**Comment by ClarkPoon** [comment]
@SijWoo do we need this mutex? Shouldn't SPI1 only be accessed by whoever has the LTC6811 mutex, and SPI3 should only be accessed by the amperes task?
