### ISSUE TITLE
[RTOS] Setup Project

### ISSUE THREAD

**Issue by SijWoo** [lhr-solar/BPS#190]
Don't work on the code just yet. Need to make sure everything compiles and the RTOS runs correctly. I'm getting an error as mentioned in issue [#171](https://github.com/lhr-solar/BPS/issues/171)

Adding skeleton code. Will update this ticket when ready.

**Comment by ClarkPoon** [comment]
@SijWoo I'm guessing this issue is resolved now?

**Comment by SijWoo** [comment]
Yesh, I will update all the issues that I fixed
