### ISSUE TITLE
Replace tabs with spaces

### ISSUE THREAD

**Issue by ClarkPoon** [lhr-solar/BPS#275]
Right now, the code has tabs and spaces mixed together. Since different text editors give tabs different sizes, the formatting of the code is inconsistent. Ideally, we would replace all tabs in the code with four spaces.

**Comment by chaseblock** [comment]
Note that the Makefile requires hard tabs to function properly. Be careful about which files you change, and be sure to run test builds afterwards.

**Comment by ClarkPoon** [comment]
I don't think this is worth the effort
