### ISSUE TITLE
Test Critical State Task

### ISSUE THREAD

**Issue by ClarkPoon** [lhr-solar/BPS#383]
We need to run the test in Tests/Test_CriticalState_1.c and Tests/Test_CriticalState_2.c to verify that the Critical State task works. Any issues that we run into when testing the Critical State task should have an issue ticket opened or a response posted here

**Comment by manthanand** [comment]
Issue: OSSemPend decremented counter whenever called so used for loop instead of while loop to run pend function 4 times. One for each post.
