### ISSUE TITLE
CAN Queue Passing Incorrect

### ISSUE THREAD

**Issue by chaseblock** [lhr-solar/BPS#387]
Currently, the queue passing for the CAN messages is implemented incorrectly. We are making use of uC/OS III's OS-level queues for message passing. This is fine, except all these do is store pointers (not full elements). Any changes to the stack or local variables before consumption will result in incorrect behavior.

This needs to be corrected.

**Comment by chaseblock** [comment]
@ClarkPoon @JimothyGreene

**Comment by ClarkPoon** [comment]
Ok. I will get this fixed
