### ISSUE TITLE
Get config.msgs to work better

### ISSUE THREAD

**Issue by manthanand** [lhr-solar/BPS#573]
If you run make, you will get this disgusting output with all the #pragmas being printed out as notes. Also some of the #defiens arent reduced to their numerical value (which is why its useful). We should make this work better.

**Comment by connorl309** [comment]
![image](https://user-images.githubusercontent.com/107018918/227731618-047bc870-bee7-46aa-b1cf-c6c15de11bd5.png)

Make will only print the macro for any defines, but any and all remaining errors are fully explained as usual. Pushing changes

**Comment by connorl309** [comment]
(Separate defines are split with a /)
