### ISSUE TITLE
Should we remove the legacy code from the repo?

### ISSUE THREAD

**Issue by chaseblock** [lhr-solar/BPS#96]
As it currently stands, the BPS repo contains `BeVolt` and `Legacy` folders at its root. Since we don't use the Legacy folder any more, I think it would make sense to remove it.

Proposed action:
1. Create a branch `legacy` from the current `master` branch and protect this to be writable only by admins. This means that if we do need/want to review legacy code in the future, it will be available without having to backtrack commits.
2. Remove the legacy code from `master` and move the code in the BeVolt folder to the root of the repository.

**Comment by SijWoo** [comment]
I’ve been thinking this, I don’t want to have the legacy code. I’m down to do your two proposed actions
